[package]
name = "paritea"
description = "Supporting Rust library for paritea"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints.rust]
missing_docs = "warn"

[dependencies]
itertools = { workspace = true }
rustworkx-core = { workspace = true }
rustc-hash = { workspace = true }
bitgauss = "0.3.4"
delegate = "0.13.5"
fraction = "0.15.4"
derive_more = { workspace = true }
